using System;
using DevExpress.Mvvm.POCO;
using DevExpress.XtraEditors;
using HidUI.Common;
using HidUI.ViewModel;
using System.Data.Entity;

namespace HidUI.Views
{
  /// <summary>
  /// Una WorkView que DEBE estar dentro de una NavigableView
  /// </summary>
  public partial class StockInsumosView : XtraUserControl, IWorkView
  {
    private StockInsumosViewModel _viewModel;

    public StockInsumosView()
    {
        InitializeComponent();
        _viewModel = ViewModelSource.Create<StockInsumosViewModel>();
        // This line of code is generated by Data Source Configuration Wizard
        // Instantiate a new DBContext
        Data.HIDContext dbContext = new Data.HIDContext();
        // Call the Load method to get the data for the given DbSet from the database.
        dbContext.Articulos.Load();
        // This line of code is generated by Data Source Configuration Wizard
        gcArticulos.DataSource = dbContext.Articulos.Local.ToBindingList();
    }

    private void NavTo_StartView(object sender, EventArgs e)
    {

    }
  }
}
